#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data efficiently

awk '{ count[$1" "$9]++ } END { for (key in count) { print count[key], key } }' apache-access.log | awk '{print $1, $2, $3}' | sort -nr

